version: '3.3'

services:
    mementoembed:
        image: oduwsdl/mementoembed:latest
        restart: always

    raintale:
        depends_on:
            - mementoembed
        image: oduwsdl/raintale:latest
        restart: always
        volumes: 
            - .:/raintale-work
        stdin_open: true
